# Generated by Django 5.2.2 on 2025-07-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('password', models.TextField(max_length=100)),
                ('number', models.IntegerField(blank=True)),
            ],
        ),
    ]
